name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit-and-e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependancies
        run: npm ci
        working-directory: ./app

      - name: Run unit tests
        run: npm  test
        working-directory: app/

      - name: Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          command: npx cypress run
